---
  - name: assign static address to cluster interface
    nmcli:
      type: ethernet
      conn_name: "System {{ networks.cls.iface }}"
      ip4: "{{ addresses.cls_ip4 }}/{{ networks.cls.prefix }}"
      ifname: "{{ networks.cls.iface }}"
      state: present
    notify:
    - restart networking

  - name: really make static (bug in nmcli module)
    shell:
      nmcli con mod "System {{ networks.cls.iface }}" ipv4.method manual


