---
- name: Setup NAT
  shell: |
    echo net.ipv4.ip_forward=1 > /etc/sysctl.conf
    sysctl -p
    firewall-cmd --permanent --zone=dmz --change-interface={{ oob_iface }}
    firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -o {{ oob_iface }} -s 172.16.3.0/24 -j MASQUERADE
    firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i {{ sys_iface }} -o {{ oob_iface }} -j ACCEPT
    firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i {{ sys_iface }} -o {{ oob_iface }} -m state --state RELATED,ESTABLISHED -j ACCEPT

  notify:
      - reload fw

- name: trust mgmt network
  shell: |
    firewall-cmd --zone=trusted --change-interface={{ sys_iface }}
  notify:
    - reload fw