---
- name: Setup NAT
  shell: |
    echo net.ipv4.ip_forward=1 > /etc/sysctl.conf
    sysctl -p
    firewall-cmd --permanent --zone=dmz --change-interface={{ networks.oob.iface }}
    firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -o {{ networks.oob.iface }} -s {{ networks.mgt.ip4 }}/{{ networks.mgt.prefix }} -j MASQUERADE
    firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i {{ networks.mgt.iface }} -o {{ networks.oob.iface }} -j ACCEPT
    firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -i {{ networks.mgt.iface }} -o {{ networks.oob.iface }} -m state --state RELATED,ESTABLISHED -j ACCEPT

  notify:
      - reload fw

- name: trust mgmt network
  shell: |
    firewall-cmd --zone=trusted --change-interface={{ networks.mgt.iface }}
  notify:
    - reload fw