all:
  vars:
    ansible_user_key: "/home/ansible/.ssh/mghpcc_osn_id_rsa.pub"
  children:
    monitors:
      hosts:
        mon01:
          ansible_host: 172.16.3.11 # eno1
          # onboard
          bmc_iface_ip4: 172.16.3.21 # bmc
          svc_iface_ip4: 172.16.3.11 # eno1
          oob_iface_ip4: 192.69.102.26 # eno2
          # mellanox
          cls_iface_ip4: 172.16.2.11 # p3p1, enp23s0
          dmz_iface_ip4: 192.69.103.246 # p1p1, enp179s0
        mon02:
          ansible_host: 172.16.3.12
          bmc_iface_ip4: 172.16.3.22
          svc_iface_ip4: 172.16.3.12
          oob_iface_ip4: 192.69.102.28
          cls_iface_ip4: 172.16.2.12
          dmz_iface_ip4: 192.69.103.247
        mon03:
          ansible_host: 172.16.3.13
          bmc_iface_ip4: 172.16.3.23
          svc_iface_ip4: 172.16.3.13
          oob_iface_ip4: 192.69.102.29
          cls_iface_ip4: 172.16.2.13
          dmz_iface_ip4: 192.69.103.248
      vars:
        sys_iface: eno1
        oob_iface: eno2
        cls_iface: enp23s0
        dmz_iface: enp179s0

    ceph:
      hosts:
        dat01:
          ansible_host: 172.16.3.111 # eno1
          # onboard
          bmc_iface_ip4: 172.16.3.121 # bmc
          svc_iface_ip4: 172.16.3.111 # eno1
          # mellanox
          cls_iface_ip4: 172.16.2.111 # p6p1, enp101s0
        dat02:
          ansible_host: 172.16.3.112
          bmc_iface_ip4: 172.16.3.122
          svc_iface_ip4: 172.16.3.112
          cls_iface_ip4: 172.16.2.112
        dat03:
          ansible_host: 172.16.3.113
          bmc_iface_ip4: 172.16.3.123
          svc_iface_ip4: 172.16.3.113
          cls_iface_ip4: 172.16.2.113
        dat04:
          ansible_host: 172.16.3.114
          bmc_iface_ip4: 172.16.3.124
          svc_iface_ip4: 172.16.3.114
          cls_iface_ip4: 172.16.2.114
        dat05:
          ansible_host: 172.16.3.115
          bmc_iface_ip4: 172.16.3.125
          svc_iface_ip4: 172.16.3.115
          cls_iface_ip4: 172.16.2.115
      vars:
        sys_iface: eno1
        cls_iface: enp101s0
    
    gateway:
      hosts:
        mon02:




