all:
  vars:
    ansible_user_key: osn_ansible_id_rsa.pub
    ansible_user: ansible
    ansible_become: yes
    site_id: "{{ lookup('env','SITE_ID') }}"
    networking: "{{ osn_networking.all_sites | combine(osn_networking[site_id], recursive=True) }}"

  children:
    monitors:
      vars:
        networks: "{{networking.networks | combine({'cls': {'iface': networking.networks.cls.iface.mon}}, recursive=True)}}"
      hosts:
        mon01:
          addresses: "{{ networking.mon01 }}"
          ansible_host: "{{ networking.mon01.mgt_ip4 }}"
        mon02:
          addresses: "{{ networking.mon02 }}"
          ansible_host: "{{ networking.mon02.mgt_ip4 }}"
        mon03:
          addresses: "{{ networking.mon03 }}"
          ansible_host: "{{ networking.mon03.mgt_ip4 }}"

    osds:
      vars:
        networks: "{{networking.networks | combine({'cls': {'iface': networking.networks.cls.iface.dat}}, recursive=True)}}"
      hosts:
        dat01:
          addresses: "{{ networking.dat01 }}"
          ansible_host: "{{ networking.dat01.mgt_ip4 }}"
        dat02:
          addresses: "{{ networking.dat02 }}"
          ansible_host: "{{ networking.dat02.mgt_ip4 }}"
        dat03:
          addresses: "{{ networking.dat03 }}"
          ansible_host: "{{ networking.dat03.mgt_ip4 }}"
        dat04:
          addresses: "{{ networking.dat04 }}"
          ansible_host: "{{ networking.dat04.mgt_ip4 }}"
        dat05:
          addresses: "{{ networking.dat05 }}"
          ansible_host: "{{ networking.dat05.mgt_ip4 }}"

    gateway:
      hosts:
        mon02
    





