- hosts: gateway
  vars_prompt:
    - name: reboot
      prompt: "Reboot after refresh? [y|N]"
      private: no
      default: "N"

  vars:
    ansible_user: ansible
    release_tag: "osn_centos7_minimal_v1.0.2"
    iso_asset: "20190912_osn_centos7_minimal.iso"
    checksum: "1659403818f230dae48bead3688f36c9"
    #removable_drive: "/dev/sdcxxx"
  become: yes
  tasks:

    - name: Find install drive
      set_fact:
        removable_drive: "/dev/{{ item.key }}"
      loop: "{{ ansible_devices|dict2items }}"
      when: (item.value.removable == "1") and (removable_drive is not defined)
      no_log: True

    - name: Get confirmation before disk wipe 
      pause: 
        prompt: |
          This script will erase everything on {{ removable_drive }} on host {{ inventory_hostname }}. 
          Press return to continue or press Ctrl+c and then "a" to abort.

    - name: pull latest release iso
      get_url:
        url: "https://github.com/OpenStorageNetwork/baremetal/releases/download/{{ release_tag }}/{{ iso_asset}}"
        dest: "/home/ansible/boot.iso"
        checksum: "md5:{{ checksum }}"

    - debug:
        msg: "The target is {{ removable_drive }}"

    - name: refresh USB drive
      shell: |
        dd bs=4M if=/home/ansible/boot.iso of="{{ removable_drive }}" conv=fdatasync status=none

    - name: reboot mon02
      shell:
        /home/ansible/utilities/IPMICFG/IPMICFG-Linux.x86_64 -reset 6
      when: reboot|lower == "y"

